site_name: gresiblos
site_url: https://github.com/dkrajzew/gresiblos
site_description: greyrat's simple blog system.
site_author: Daniel Krajzewicz
docs_dir: ./docs

repo_url: https://github.com/dkrajzew/gresiblos
edit_uri: ""

theme:
    name: material
    custom_dir: ./docs/materials_ext
    font: false
    palette:
        primary: red

extra_css:
    - stylesheets/extra.css
    - stylesheets/prism.css

extra_javascript:
    - js/prism.js

nav:
    - Home: index.md
    - Installation: install.md
    - Usage: usage.md
    - Command Line: cmd.md
    - Links: links.md
    - API: api_gresiblos.md
    - ChangeLog: changes.md
    - License (BSD): license.md
    - Legal: legal.md

markdown_extensions:
    - admonition
    - sane_lists

copyright: "&copy; Copyright 2016&ndash;2025, Daniel Krajzewicz."

use_directory_urls: false

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                paths: [./gresiblos]
                options:
                    filters: [""]
                    show_source: False
                    docstring_style: "google"